### ISSUE TITLE
hey! 

### ISSUE THREAD

**Issue by LEVIXDDLMAO** [JuniorNovoa1/Indie-Cross-V1.5-NOT-DONE#1]
Can i ask something?

**Comment by MemeHoovy** [comment]
levi, this repo is dead, I don't know if they're gonna respond or not 🤷🏻‍♂️

**Comment by BushTrain460615** [comment]
the project Is dead

**Comment by LEVIXDDLMAO** [comment]
is there any way i can get some help with heath bars and the song title thing?

**Comment by JuniorNovoa1** [comment]
So like I'm too lazy to show you how to do it, so you can just take them from this repo, all I ask is for me and bush to receive credit.
